# 1. Numpy and Linear Algebra (선형대수)

- 수치 data 를 다루는데 효율적이고 높은 성능 제공

- 각종 수학적 함수 제공

- Python scientific library 들이 Numpy 기반으로 구축

### ndarray

- n-dimensional array (다차원 배열 객체) 로 구성 

In [2]:
import numpy as np

In [3]:
x=6

6

In [10]:
a = np.array([1,2,3,4,5,2,1])
print(a.shape) # 1차원 array는 vector인 튜플로 표기

(7,)


In [11]:
np.argmax(a) # 가장 큰 인덱스 값이 몇번째냐
a.argmax()

4

In [12]:
type(a)

numpy.ndarray

In [14]:
y = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [18]:
print(y.shape)
print(y.size)
print(y.argmax(axis=1)) # axis 0 , 각 열에서 가장 큰 숫자 있는 위치 표기 

(3, 3)
9
[2 2 2]


In [22]:
z = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(z)
print(z.shape) #  (2,2,3) 2,3 매트릭스가 2개(채널) -> Tensorflow 형태 / (2,3,2) 2,3매트릭스 2개 pytorch 형태

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)


<img src="axes.png" width="600">

<img src="numpy.png" width="400">



<img src="tensor.jpg" width="600">

## Slicing

<img src="numpy1.png" width="300">

In [31]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)

print(arr[:2,1:])
x=arr[2,:]
print(x,x.shape)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2 3]
 [5 6]]
[7 8 9] (3,)


In [34]:
x = arr[:,:2]
x, x.shape

(array([[1, 2],
        [4, 5],
        [7, 8]]),
 (3, 2))

In [43]:
x = arr[1,:2]
print(x, x.shape)
x = arr[1:2,:2] # 매트릭스로 뽑는방법
x, x.shape

[4 5] (2,)


(array([[4, 5]]), (1, 2))

### 벡터의 내적(inner product)  - (딥러닝 내부에서 일어나는 연산)
- 내적이 되려면 두 벡터의 dimension 이 같아야 한다. 내적은 각 element 의 곱을 모두 더한 것이다.
- inner product 은 dot product (점곱) 이라고도 불린다.

$\mathbf{a}\mathbf{b}^T = \begin{bmatrix} 2 & 5 & 1\end{bmatrix}\begin{bmatrix}4\\3\\5\end{bmatrix} = \begin{bmatrix}2*4 + 5*3 + 1*5\end{bmatrix} = 28$

## matrix 곱셈 (행렬 곱셈, dot product)

### 두 행렬 A 와 B 는 A 의 열(column) 갯수가 B 의 행(row) 갯수와 같을 때 곱할 수 있다. 결과 행렬 C 의 shape 은 A 의 row x B 의 column 이 된다.

<img src="matmul2.png" width="250">
<img src="matmul.png" width="350">

$$\mathbf{A} = \begin{bmatrix}2&5&1\\4&5&3\end{bmatrix} \text{ and } \mathbf{B}=\begin{bmatrix}4&3&5&7\\9&5&3&4\\5&3&6&7\end{bmatrix}$$
$$\mathbf{AB} = \begin{bmatrix}2*4+5*9+1*5&2*3+5*5+1*3&2*5+5*3+1*6&2*7+5*4+1*7\\4*4+5*9+3*5&4*3+5*5+3*3&4*5+5*3+3*6&4*7+5*4+3*7\end{bmatrix}$$

In [48]:
a = np.array([[2,1],[1,4]])
b= np.array([[1,2,0],[0,1,2]])
print(a,b)

[[2 1]
 [1 4]] [[1 2 0]
 [0 1 2]]


In [49]:
# 행렬 곱셈
np.matmul(a,b)

array([[2, 5, 2],
       [1, 6, 8]])

### 전치행렬 (Transposed Matrix) - 행과 열을 바꿔주는 것

In [60]:
A = np.arange(9).reshape(3,3)
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [61]:
A.T # 행과 열을 바꿔주는 것

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [63]:
np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [70]:
np.random?

In [75]:
import pandas as pd

np.random.seed(0)
data = np.random.randn(5,4) # 5,4 배열로 0과 1사이 난수 발생
data

array([[ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ],
       [ 1.86755799, -0.97727788,  0.95008842, -0.15135721],
       [-0.10321885,  0.4105985 ,  0.14404357,  1.45427351],
       [ 0.76103773,  0.12167502,  0.44386323,  0.33367433],
       [ 1.49407907, -0.20515826,  0.3130677 , -0.85409574]])

In [80]:
df = pd.DataFrame(data,columns=["W","X","Y","Z"])
df

W         X         Y         Z
0  1.764052  0.400157  0.978738  2.240893
1  1.867558 -0.977278  0.950088 -0.151357
2 -0.103219  0.410599  0.144044  1.454274
3  0.761038  0.121675  0.443863  0.333674
4  1.494079 -0.205158  0.313068 -0.854096

In [81]:
df.columns

Index(['W', 'X', 'Y', 'Z'], dtype='object')

In [82]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   W       5 non-null      float64
 1   X       5 non-null      float64
 2   Y       5 non-null      float64
 3   Z       5 non-null      float64
dtypes: float64(4)
memory usage: 288.0 bytes


In [83]:
df.describe()

W         X         Y         Z
count  5.000000  5.000000  5.000000  5.000000
mean   1.156702 -0.050001  0.565960  0.604678
std    0.826433  0.576234  0.379083  1.242182
min   -0.103219 -0.977278  0.144044 -0.854096
25%    0.761038 -0.205158  0.313068 -0.151357
50%    1.494079  0.121675  0.443863  0.333674
75%    1.764052  0.400157  0.950088  1.454274
max    1.867558  0.410599  0.978738  2.240893

In [84]:
type(df)

pandas.core.frame.DataFrame

In [86]:
df["W"]
df.W

0    1.764052
1    1.867558
2   -0.103219
3    0.761038
4    1.494079
Name: W, dtype: float64

In [87]:
df[["W","X"]]

W         X
0  1.764052  0.400157
1  1.867558 -0.977278
2 -0.103219  0.410599
3  0.761038  0.121675
4  1.494079 -0.205158

In [88]:
# 새 컬럼 생성
df['new'] = df['W']+df['X']
df

W         X         Y         Z       new
0  1.764052  0.400157  0.978738  2.240893  2.164210
1  1.867558 -0.977278  0.950088 -0.151357  0.890280
2 -0.103219  0.410599  0.144044  1.454274  0.307380
3  0.761038  0.121675  0.443863  0.333674  0.882713
4  1.494079 -0.205158  0.313068 -0.854096  1.288921

In [93]:
# 컬럼 삭제
df.drop('new',axis=1, inplace=True) # inplace=True 원본 업데이트

In [94]:
df

W         X         Y         Z
0  1.764052  0.400157  0.978738  2.240893
1  1.867558 -0.977278  0.950088 -0.151357
2 -0.103219  0.410599  0.144044  1.454274
3  0.761038  0.121675  0.443863  0.333674
4  1.494079 -0.205158  0.313068 -0.854096

#### missing data

In [96]:
df = pd.DataFrame('A'[1,2,np.nan],
                  'B'[5,np.nan,np.nan],
                  'C'[1,2,3])
df

<>:1: SyntaxWarning: str indices must be integers or slices, not tuple; perhaps you missed a comma?
<>:2: SyntaxWarning: str indices must be integers or slices, not tuple; perhaps you missed a comma?
<>:3: SyntaxWarning: str indices must be integers or slices, not tuple; perhaps you missed a comma?
<>:1: SyntaxWarning: str indices must be integers or slices, not tuple; perhaps you missed a comma?
<>:2: SyntaxWarning: str indices must be integers or slices, not tuple; perhaps you missed a comma?
<>:3: SyntaxWarning: str indices must be integers or slices, not tuple; perhaps you missed a comma?
<ipython-input-96-b48d4bf4e84c>:1: SyntaxWarning: str indices must be integers or slices, not tuple; perhaps you missed a comma?
  df = pd.DataFrame('A'[1,2,np.nan],
<ipython-input-96-b48d4bf4e84c>:2: SyntaxWarning: str indices must be integers or slices, not tuple; perhaps you missed a comma?
  'B'[5,np.nan,np.nan],
<ipython-input-96-b48d4bf4e84c>:3: SyntaxWarning: str indices must be integers or

TypeError: string indices must be integers

In [97]:
df.fillna(0,inplace=True)

In [98]:
df

W         X         Y         Z
0  1.764052  0.400157  0.978738  2.240893
1  1.867558 -0.977278  0.950088 -0.151357
2 -0.103219  0.410599  0.144044  1.454274
3  0.761038  0.121675  0.443863  0.333674
4  1.494079 -0.205158  0.313068 -0.854096

In [101]:
import torch
import numpy as np
import matplotlib.pyplot as plt

device = "cuda:0" if torch.cuda.is_available() else "cpu"
device

'cuda:0'

In [102]:
torch.__version__

'1.10.2'

Float torch 생성

In [106]:
a = np.ones((2,3))

b = torch.tensor(a)
print(a.dtype, b.dtype)

float64 torch.float64


In [109]:
x = torch.tensor([[1,2,3],[4,5,6]], dtype=torch.int32,device=device)
x

tensor([[1, 2, 3],
        [4, 5, 6]], device='cuda:0', dtype=torch.int32)